### PR TITLE
Fix requirejs/nodejs definition, fix three @param comments

### PR DESCRIPTION
**Pull request by Rycochet**
The whole file being green is indentation - the only code additions are at the very top and bottom, plus three of the param comments that weren't correct so showing up in my editor.

### CODE REVIEW

**Comment by ArtskydJ** [comment]
Viewable diff: https://github.com/ddo/oauth-1.0a/pull/31/files?w=1

**Comment by kaidjohnson** [comment]
The UMD addition here is a must-have and would be great to see get merged in.

One note: you probably want to check AMD first, then CommonJS, given the conversation at https://github.com/umdjs/umd/pull/22

**Comment by ddo** [comment]
i will be back from travel next week. i will recheck all the pr soon

**Comment by ddo** [comment]
pls make a new PR for v2.0.0 ty

**Pull request closed without merging**
