### PR TITLE
Make realm optional in TS.

### LINKED ISSUE #71: Fix typings
Make realm parameter in options optional.

### PR DESCRIPTION
**Pull request by jasonmerino**
Resolves #71

### CODE REVIEW

**Comment by ddo** [comment]
ty

**Comment by astephenb** [comment]
@ddo Is it possible to publish this soon?

**Comment by ddo** [comment]
yes trying to solve some other issues

**Comment by astephenb** [comment]
No worries. Thanks for the update!

**Comment by ddo** [comment]
v2.2.5 is now available. ty

**Pull request merged**
