### PR TITLE
Add body_hash_function for oauth_body_hash signature

### LINKED ISSUE #65: Body hash should be generated using SHA1
Body Hash signature currently uses `hash_function ` option, typically a "HMAC-SHA1" signature function instead of "SHA1".

It should instead use a `body_hash_function ` option, default `body_hash_function` to the `hash_function ` option, deprecate defaulting to `hash_function ` in version `<3.0.0` and remove the default in `v3.0.0`.

Reference:

- [OBH draft](https://tools.ietf.org/id/draft-eaton-oauth-bodyhash-00.html#anchor3)
- [Request's implementation](https://github.com/request/request/blob/253c5e507ddb95dd88622087b6387655bd0ff935/lib/oauth.js#L64)

### PR DESCRIPTION
**Pull request by dinoboff**
According to the [OAuth Request Body Hash draft], the oauth_body_hash algorithm for HMAC-SHA1 or RSA-SHA1 Oauth signature methods should be SHA1 (not HMAC-SHA1/RSA-SHA1). This patch keep using the default hash function for the body hash but allows to define an alternative one via the `body_hash_function` initial option.

[OAuth Request Body Hash draft]: https://tools.ietf.org/id/draft-eaton-oauth-bodyhash-00.html#anchor3

Fix #65

### CODE REVIEW

**Comment by ddo** [comment]
ty I gonna check this on weekend

**Comment by dinoboff** [comment]
@ddo the use case for the patch implementing OBH was a LTI specification about server to server communication. Its implementation guide describe how to implement OBH:

> The oauth_body_hash is computed using a SHA-1 hash of the body contents and added to the Authorization header.

https://www.imsglobal.org/specs/ltiv2p0/implementation-guide#toc-41

**Comment by dinoboff** [comment]
@ddo Did you have a chance to look at it?

**Comment by ddo** [comment]
thanks @dinoboff very much

**Pull request merged**
