### PR TITLE
preserve sorted parameters - allows working with JIRA

### PR DESCRIPTION
**Pull request by asharpe-squiz**
See https://tools.ietf.org/html/rfc5849#section-3.4.1.3.2

### CODE REVIEW

**Comment by ddo** [comment]
ty.

it's called at [line 134](https://github.com/asharpe-squiz/oauth-1.0a/blob/7fa55bddab83ec21d0f31c1f6f08c6b597f8450c/oauth-1.0a.js#L134) and [line 136](https://github.com/asharpe-squiz/oauth-1.0a/blob/7fa55bddab83ec21d0f31c1f6f08c6b597f8450c/oauth-1.0a.js#L136) also.

**Comment by asharpe-squiz** [comment]
I believe those calls have already been dealt with.  Please check the diff again and let me know.

**Comment by asharpe-squiz** [comment]
Tested this code against JIRA 6 and it's working

**Comment by ddo** [comment]
please check the new commit, then we can merge this PR

**Comment by asharpe-squiz** [comment]
That's great!  I added one more change to stop parameters like "x_custom_oauth_thing" getting into the Authorization header

**Comment by ddo** [comment]
ty

**Comment by gits2501** [comment]
Im sorry to interrupt you're pull req' thread. But as far I understand you're offering option of you library to work directly in browser. This mean that consumer secret and key that suppose to be private are hard coded into script (feeded as an plain javascript object with plain text strings as a secret and a key). That means I could:
- visit website that uses your  library,
- exam the script that uses your library and copy paste consumer secret and key 
- make exact site like one I visited
- and since I have that website's/app's consumer key and secret  I can make valid request sfor tokens 
- and do very dishonest action towards user pool of the site I fake

As far as I know, twitter for example does not enforce callback URL's to be same. Meaning afther I make fake site and user approve my request to act in their name, callback url that twitter is redirecting that user can be anything. Because callback is sett dynamically trough  javascript in [request tokens step](https://dev.twitter.com/oauth/reference/post/oauth/request_token) 
I'm I missing something here?!

**Comment by ddo** [comment]
hi

https://github.com/ddo/oauth-1.0a#client-side-usage-caution

**Comment by gits2501** [comment]
How this have anything to do with CORS? It has to do with javascript object that has stored plain text as consumer secret and key. CORS is security against accesing resources across domain that do not support at least JSONP or when server does not emit " Access Control Allow Origin:* " header. Twitter  emits that header, no CORS policy applies.

**Comment by ddo** [comment]
ty, PR is welcome.

**Pull request merged**
