### PR TITLE
makes e2e tests optionals and ease their setup

### PR DESCRIPTION
**Pull request by dinoboff**
- [x] Skip tests requiring missing environment variable.
- [x] Support dotenv to manage tests' environment variable.
- [x] refactor npm run test to not require `make`.
- [x] add coverage task (text report).
- [x] refactor makefile (only rerun test if necessary before running coverage, move mocha config to `opts.mocha`).

Each e2e tests are skipped unless the consumer keys/secret they require are set (as environment variable).

`make .env` create a ".env" with the environment variables required by those tests; they will be loaded into `process.env` by mocha. You still need to go register an app with each services but it's easier to load them into env.

Note that variables set in ".env" should not override env variables already set.

### CODE REVIEW

**Comment by ddo** [comment]
i think this PR and #69 is shuffle?

**Comment by dinoboff** [comment]
I based #69 from this one so I could test #69. I am happy to rebase #69 on master instead.

**Comment by ddo** [comment]
merged thanks

**Comment by dinoboff** [comment]
@ddo which node versions does it need to support?

This PR updates mocha to support "test/opts.mocha", but the latest version drops supports for node v0.10 and node v0.12. If it needs to run the tests in node v0.x, mocha@3 can be used instead.

**Comment by ddo** [comment]
@dinoboff it's ok to ignore node v0.x i think

**Pull request merged**
