### PR TITLE
sort parameters properly - allows working with JIRA

### PR DESCRIPTION
**Pull request by asharpe-squiz**

### CODE REVIEW

**Comment by ddo** [comment]
hi, could you give me the JIRA document about this. ty

**Comment by asharpe-squiz** [comment]
I don't think the JIRA docs will be helpful here, what's more relevant is
https://tools.ietf.org/html/rfc5849#section-3.4.1.3.2, specifically

2.  The parameters are sorted by name, using ascending byte value
>        ordering.  If two or more parameters share the same name, they
>        are sorted by their value.


The original version is relying on the order of object keys which I don't
think is guaranteed in javascript!  That's why you must use an array to
sort the keys, which was being done, however then the values where thrown
straight back into an object, effectively undoing the sort.

Hope that helps :)

**Comment by ddo** [comment]
* so you need to revise the ``OAuth.prototype.sortObject`` and also where it's called
* why ``oauth_signature`` always at the last?

**Comment by asharpe-squiz** [comment]
I'm going to close this request and open another which makes the changes in sortObject

**Pull request closed without merging**
